/**
 * B1 kelime deposu — **sadece veri.**
 *
 * Bu klasör kelime havuzunun "veri merkezi": mantık `../wordbank.ts` içinde,
 * kelimeler burada. Ayrı durmalarının sebebi kullanıcının şikâyeti:
 * *"burası karışık, havuzu 0'dan düzenleyelim, bir model oluşturmamız lazım."*
 * Veri ile mantık aynı dosyadayken havuzu büyütmek her seferinde 1000 satırlık
 * bir dosyayı kurcalamak demekti; şimdi seviyenin listesi tek başına duruyor.
 *
 * Buraya kelime eklemeden önce `npm run kelime` kurallarını oku — denetçi
 * seviyeyi, örnek cümledeki kelimeleri ve tür dengesini kontrol ediyor.
 */

import type { Group } from './types';

export const B1_WORDS: Group = {
  isim: [
    ['advice', 'tavsiye, öğüt', 'She gave me some useful advice about the job.'],
    ['opinion', 'görüş, fikir', 'In my opinion, the plan is too risky.'],
    ['experience', 'deneyim, tecrübe', 'He has ten years of experience in finance.'],
    ['opportunity', 'fırsat', 'This is a good opportunity to practise.'],
    ['progress', 'ilerleme', 'You have made real progress this month.'],
    ['effort', 'çaba', 'It took a lot of effort to finish.'],
    ['purpose', 'amaç', 'What is the purpose of this meeting?'],
    ['attitude', 'tutum, tavır', 'Her attitude to work has changed.'],
    ['behaviour', 'davranış', 'His behaviour surprised everyone.'],
    ['relationship', 'ilişki', 'They have a good working relationship.'],
    ['responsibility', 'sorumluluk', 'Taking responsibility is not always easy.'],
    ['confidence', 'özgüven, güven', 'Speaking every day builds confidence.'],
    ['pressure', 'baskı', 'There is a lot of pressure before the deadline.'],
    ['deadline', 'son teslim tarihi', 'We missed the deadline by two days.'],
    ['budget', 'bütçe', 'The project went over budget.'],
    ['income', 'gelir', 'Most of his income comes from teaching.'],
    ['benefit', 'fayda, yarar', 'The main benefit is saving time.'],
    ['advantage', 'avantaj, üstünlük', 'Living near the office is a big advantage.'],
    ['solution', 'çözüm', 'We finally found a simple solution.'],
    ['detail', 'ayrıntı', 'He explained the plan in detail.'],
    ['skill', 'beceri', 'Listening is a skill you can train.'],
    ['knowledge', 'bilgi, birikim', 'Her knowledge of the market is useful.'],
    ['research', 'araştırma', 'The research took almost a year.'],
    ['society', 'toplum', 'These changes affect the whole society.'],
    ['government', 'hükümet', 'The government announced a new rule.'],
    ['environment', 'çevre, ortam', 'We work in a relaxed environment.'],
    ['population', 'nüfus', 'The population of the city is growing.'],
  ],
  fiil: [
    ['achieve', 'başarmak, elde etmek', 'She achieved her goal in six months.'],
    ['avoid', 'kaçınmak, sakınmak', 'I try to avoid arguments at work.'],
    ['suggest', 'önermek', 'I suggest starting with the easy part.'],
    ['require', 'gerektirmek', 'This job requires a lot of patience.'],
    ['consider', 'göz önünde bulundurmak', 'Consider the cost before you decide.'],
    ['prevent', 'engellemek, önlemek', 'A short break prevents mistakes.'],
    ['increase', 'artmak, artırmak', 'Prices increased again this year.'],
    ['reduce', 'azaltmak', 'We need to reduce our expenses.'],
    ['affect', 'etkilemek', 'The delay affected the whole plan.'],
    ['depend', 'bağlı olmak', 'It depends on the weather.'],
    ['realise', 'fark etmek, anlamak', 'I did not realise how late it was.'],
    ['notice', 'fark etmek', 'I did not notice the mistake at first.'],
    ['admit', 'kabul etmek, itiraf etmek', 'He admitted that he was wrong.'],
    ['refuse', 'reddetmek', 'She refused to change her mind.'],
    ['complain', 'şikâyet etmek', 'Several customers complained about the delay.'],
    ['apologise', 'özür dilemek', 'He apologised for being late.'],
    ['encourage', 'teşvik etmek', 'My teacher encouraged me to try again.'],
    ['recommend', 'tavsiye etmek', 'I recommend this book to everyone.'],
    ['deserve', 'hak etmek', 'After that week, you deserve a rest.'],
    ['expect', 'beklemek, ummak', 'I did not expect such a good result.'],
    ['allow', 'izin vermek', 'They do not allow phones in the exam.'],
    ['succeed', 'başarılı olmak', 'She succeeded after a long year.'],
    ['accept', 'kabul etmek', 'He accepted the offer immediately.'],
    ['apply', 'başvurmak, uygulamak', 'I applied for the job last week.'],
    ['provide', 'sağlamak', 'The company provides free lunch.'],
    ['prefer', 'tercih etmek', 'I prefer working in the morning.'],
    ['manage', 'becermek, üstesinden gelmek', 'I managed to finish before lunch.'],
    ['discuss', 'tartışmak, görüşmek', 'We discussed the problem for an hour.'],
    ['compare', 'kıyaslamak', 'Compare last year with this year.'],
  ],
  sıfat: [
    ['worth', 'değer, değmek', 'The trip was long, but it was worth it.'],
    ['reliable', 'güvenilir', 'He is the most reliable person on the team.'],
    ['aware', 'farkında', 'I was not aware of the new rule.'],
    ['common', 'yaygın, ortak', 'This mistake is very common.'],
    ['confident', 'kendine güvenen', 'She sounded confident in the meeting.'],
    ['curious', 'meraklı', 'I am curious about your new job.'],
    ['disappointed', 'hayal kırıklığına uğramış', 'He was disappointed with the result.'],
    ['embarrassed', 'utanmış, mahcup', 'I felt embarrassed after my mistake.'],
    ['essential', 'gerekli, şart', 'Practice is essential for progress.'],
    ['familiar', 'tanıdık, aşina', 'This street looks familiar to me.'],
    ['honest', 'dürüst', 'To be honest, I did not like it.'],
    ['obvious', 'apaçık, belli', 'The answer was obvious to everyone.'],
    ['ordinary', 'sıradan, olağan', 'It was an ordinary Tuesday morning.'],
    ['patient', 'sabırlı', 'You must be patient with beginners.'],
    ['proud', 'gururlu', 'I am proud of your progress.'],
    ['serious', 'ciddi', 'This is a serious problem.'],
    ['similar', 'benzer', 'Our situations are quite similar.'],
    ['suitable', 'uygun', 'This film is not suitable for children.'],
    ['typical', 'tipik', 'That is typical of him.'],
    ['unusual', 'alışılmadık', 'It is unusual for her to be late.'],
    ['valuable', 'değerli', 'Your advice was really valuable.'],
  ],
  zarf: [
    ['probably', 'muhtemelen', 'He will probably arrive late.'],
    ['actually', 'aslında', 'Actually, I have never been there.'],
    ['especially', 'özellikle', 'I like Sundays, especially the mornings.'],
    ['recently', 'son zamanlarda', 'I have recently started running.'],
    ['suddenly', 'aniden', 'Suddenly, the lights went out.'],
    ['hardly', 'neredeyse hiç', 'I hardly know him.'],
    ['instead', 'onun yerine', 'We stayed home instead.'],
    ['exactly', 'tam olarak', 'That is exactly what I meant.'],
  ],
};
