/**
 * A1 fazı — **çeşitlilik havuzu.**
 *
 * Kullanıcının bildirimi: *"bilimi seçtim SciShow verdi, çıktım girdim
 * yeniden bilim seçtim yine aynısı… sürekli SciShow görmesin bilimdeki,
 * spor seçen sürekli maç görmesin."*
 *
 * `a1.ts` her zevk anahtarını **birer** içerikle karşılıyordu: kapsam tamdı
 * ama çeşitlilik yoktu, bir hobinin tek karşılığı vardı. Bu dosya her
 * anahtara 2-3 alternatif ekliyor; seçim `pickLocalContent` içinde zevklerin
 * kaydedilme anına da bağlı olduğu için Zevklerim'e girip kaydettiğinde
 * havuzdan başka bir öğe geliyor.
 *
 * Ölçüt `a1.ts` ile aynı: gerçek dizi yok, A1'de anlaşılabilir olacak,
 * uydurma bağlantı yok — arama terimi veriliyor.
 *
 * Etiketler dar tutuldu: `localcontent.ts` eşitlikte dar etiketli içeriği
 * kazandırıyor, geniş etiket koymak başka hobilerin önünü keser.
 */

import type { CatalogItem } from './types';

export const A1_CESIT: CatalogItem[] = [
  /* ══════════════════════════════════════════════════════════ BİLİM */
  {
    id: 'a1c-bilim-peekaboo',
    type: 'youtube',
    title: 'Peekaboo Kidz · basit fen anlatımı',
    where: 'YouTube — "Peekaboo Kidz" ara',
    levels: ['A1'],
    tastes: ['bilim'],
    why: 'Bilim seçtin. Bu videolar bir soruyu ("neden gökyüzü mavi?") çizimlerle ve çok basit cümlelerle anlatıyor.',
    instruction: 'Bir video izle, 5 dakika. Sorulan soruyu ve cevabı İngilizce tek cümleyle yaz.',
    words: [
      { word: 'to explain', meaning: 'açıklamak' },
      { word: 'reason', meaning: 'sebep' },
      { word: 'air', meaning: 'hava' },
      { word: 'light', meaning: 'ışık' },
    ],
    watchFor: ['Soru nasıl soruluyor?', 'Cevap hangi kelimeyle başlıyor?'],
    noun: 'video',
  },
  {
    id: 'a1c-bilim-deney',
    type: 'youtube',
    title: 'Evde basit deneyler · İngilizce anlatım',
    where: 'YouTube — "easy science experiments for kids" ara',
    levels: ['A1'],
    tastes: ['bilim'],
    why: 'Bilim seçtin. Deney videolarında her adım hem söyleniyor hem yapılıyor; emir cümlelerini görerek öğreniyorsun.',
    instruction: 'Bir deney videosu izle ve adımları İngilizce yaz. İstersen deneyi de yap.',
    words: [
      { word: 'to pour', meaning: 'dökmek' },
      { word: 'to mix', meaning: 'karıştırmak' },
      { word: 'water', meaning: 'su' },
      { word: 'to watch', meaning: 'izlemek, gözlemek' },
    ],
    watchFor: ['Kaç emir cümlesi duydun?', 'Sonucu nasıl anlatıyor?'],
    noun: 'video',
  },

  /* ═══════════════════════════════════════════════ TARİH VE BELGESEL */
  {
    id: 'a1c-belgesel-natgeo',
    type: 'youtube',
    title: 'Nat Geo Kids · kısa doğa videoları',
    where: 'YouTube — "Nat Geo Kids" ara',
    levels: ['A1'],
    tastes: ['belgesel', 'dizi'],
    why: 'Belgesel seçtin. Bu videolar 3-4 dakika ve anlatım çocuklar için sadeleştirilmiş — A1\'de takip edebileceğin nadir belgesel biçimi.',
    instruction: 'İki kısa video izle. Her birinden bir hayvan adı ve bir sıfat not al.',
    words: [
      { word: 'wild', meaning: 'vahşi, yabani' },
      { word: 'to live', meaning: 'yaşamak' },
      { word: 'big / small', meaning: 'büyük / küçük' },
      { word: 'ocean', meaning: 'okyanus' },
    ],
    watchFor: ['Hayvanı tarif ederken hangi sıfatlar geçti?', 'Nerede yaşadığını nasıl söylüyor?'],
    noun: 'video',
  },
  {
    id: 'a1c-tarih-simple',
    type: 'youtube',
    title: 'Simple History · animasyonlu tarih anlatımı',
    where: 'YouTube — "Simple History" ara',
    levels: ['A1'],
    tastes: ['tarih'],
    why: 'Tarih seçtin. Animasyonlu ve kısa; olaylar görselle anlatıldığı için cümleyi kaçırsan da hikâyeyi kaybetmiyorsun.',
    instruction: 'Bir video izle, 5 dakika. Anlatılan olayı Türkçe düşün, İngilizce iki cümleyle yaz.',
    words: [
      { word: 'year', meaning: 'yıl' },
      { word: 'soldier', meaning: 'asker' },
      { word: 'to begin', meaning: 'başlamak' },
      { word: 'country', meaning: 'ülke' },
    ],
    watchFor: ['Tarihleri nasıl söylüyor?', 'Kaç geçmiş zaman fiili duydun?'],
    noun: 'video',
  },

  /* ════════════════════════════════════════════════════════════ SPOR */
  {
    id: 'a1c-futbol-roportaj',
    type: 'youtube',
    title: 'Maç sonrası röportaj · kısa',
    where: 'YouTube — "post match interview premier league" ara',
    levels: ['A1'],
    tastes: ['futbol', 'spor'],
    why: 'Futbol seçtin. Röportajlar 2-3 dakika ve sorular hep aynı kalıptan: "How do you feel?", "What happened?" — ezberlenecek kadar tekrarlı.',
    instruction: 'Bir röportaj izle. Sorulan soruları yaz, cevapları anlamaya çalışma.',
    words: [
      { word: 'How do you feel?', meaning: 'Nasıl hissediyorsun?' },
      { word: 'result', meaning: 'sonuç' },
      { word: 'difficult', meaning: 'zor' },
      { word: 'proud', meaning: 'gururlu' },
    ],
    watchFor: ['Kaç soru sorulmuş?', 'Oyuncu duygusunu nasıl anlatıyor?'],
    noun: 'video',
  },
  {
    id: 'a1c-basketbol-top10',
    type: 'youtube',
    title: 'NBA · haftanın en iyi 10 hareketi',
    where: 'YouTube — "NBA top 10 plays" ara',
    levels: ['A1'],
    tastes: ['basketbol', 'spor'],
    why: 'Basketbol seçtin. Geri sayımlı listeler A1 için iyi: sıra sayıları tekrar ediyor ve her hareket tek cümleyle anlatılıyor.',
    instruction: '5 dakikalık bir liste izle. Sıra sayılarını ve tekrar eden fiilleri yaz.',
    words: [
      { word: 'number ten / nine', meaning: 'onuncu / dokuzuncu' },
      { word: 'to jump', meaning: 'zıplamak' },
      { word: 'to pass', meaning: 'pas vermek' },
      { word: 'amazing', meaning: 'inanılmaz' },
    ],
    watchFor: ['Sıra sayıları nasıl söyleniyor?', 'En çok hangi sıfat geçti?'],
    noun: 'video',
  },
  {
    id: 'a1c-fitness-esneme',
    type: 'youtube',
    title: '10 dakikalık esneme videosu · İngilizce',
    where: 'YouTube — "10 minute stretch routine english" ara',
    levels: ['A1'],
    tastes: ['fitness', 'spor'],
    why: 'Fitness seçtin. Esneme videoları antrenmandan daha yavaş konuşur; vücut bölgelerinin adlarını hareketle birlikte öğreniyorsun.',
    instruction: '10 dakikalık bir video yap. Geçen vücut bölgesi adlarını yaz.',
    words: [
      { word: 'shoulder', meaning: 'omuz' },
      { word: 'back', meaning: 'sırt' },
      { word: 'leg', meaning: 'bacak' },
      { word: 'slowly', meaning: 'yavaşça' },
    ],
    watchFor: ['Kaç vücut bölgesi adı duydun?', '"slowly" hangi cümlelerde geçiyor?'],
    noun: 'video',
  },
  {
    id: 'a1c-dovus-teknik',
    type: 'youtube',
    title: 'Boks temel teknik anlatımı · İngilizce',
    where: 'YouTube — "basic boxing technique for beginners" ara',
    levels: ['A1'],
    tastes: ['dovus', 'spor'],
    why: 'Dövüş sporu seçtin. Teknik anlatımlarda her hareket önce söyleniyor sonra yapılıyor — kelime ile hareket eşleşiyor.',
    instruction: '10 dakikalık bir anlatım izle. Öğrendiğin hareket adlarını yaz.',
    words: [
      { word: 'punch', meaning: 'yumruk' },
      { word: 'guard', meaning: 'koruma pozisyonu' },
      { word: 'step', meaning: 'adım' },
      { word: 'to repeat', meaning: 'tekrar etmek' },
    ],
    watchFor: ['Kaç hareket adı öğrendin?', 'Emir cümleleri nasıl kuruluyor?'],
    noun: 'video',
  },
  {
    id: 'a1c-motor-nasil',
    type: 'youtube',
    title: 'Formula 1 · pit stop nasıl çalışır',
    where: 'YouTube — "how an F1 pit stop works" ara',
    levels: ['A1'],
    tastes: ['motor', 'spor'],
    why: 'Motor sporları seçtin. Açıklama videoları yarış anlatımından yavaştır; parça adlarını görüntüyle birlikte öğreniyorsun.',
    instruction: '5 dakikalık bir açıklama videosu izle. Parça adlarını yaz.',
    words: [
      { word: 'tyre / tire', meaning: 'lastik' },
      { word: 'to change', meaning: 'değiştirmek' },
      { word: 'second', meaning: 'saniye' },
      { word: 'team', meaning: 'takım' },
    ],
    watchFor: ['Süreleri nasıl söylüyor?', 'Kaç parça adı geçti?'],
    noun: 'video',
  },
  {
    id: 'a1c-kosu-ipucu',
    type: 'youtube',
    title: 'Yeni başlayanlar için koşu ipuçları',
    where: 'YouTube — "running tips for beginners" ara',
    levels: ['A1'],
    tastes: ['kosu', 'spor'],
    why: 'Koşu seçtin. İpucu videoları maddeler hâlinde ilerler ("first…, second…"); sıralama kalıplarını doğal yolla öğreniyorsun.',
    instruction: '10 dakikalık bir video izle. Verilen tavsiyeleri madde madde yaz.',
    words: [
      { word: 'to breathe', meaning: 'nefes almak' },
      { word: 'shoes', meaning: 'ayakkabı' },
      { word: 'to start slowly', meaning: 'yavaş başlamak' },
      { word: 'every day', meaning: 'her gün' },
    ],
    watchFor: ['Kaç tavsiye verdi?', 'Sıralarken hangi kelimeleri kullandı?'],
    noun: 'video',
  },
  {
    id: 'a1c-tenis-ders',
    type: 'youtube',
    title: 'Tenis dersi · temel vuruşlar',
    where: 'YouTube — "tennis lesson for beginners" ara',
    levels: ['A1'],
    tastes: ['tenis', 'spor'],
    why: 'Tenis seçtin. Ders videolarında her vuruş yavaş yavaş, tekrar tekrar anlatılıyor — tekrar A1\'de en iyi öğretmendir.',
    instruction: '10 dakikalık bir ders izle. Vuruş adlarını ve verilen emirleri yaz.',
    words: [
      { word: 'forehand', meaning: 'düz vuruş' },
      { word: 'to hold', meaning: 'tutmak' },
      { word: 'racket', meaning: 'raket' },
      { word: 'again', meaning: 'tekrar' },
    ],
    watchFor: ['"again" kaç kez geçti?', 'Vuruş adlarını sayabildin mi?'],
    noun: 'video',
  },
  {
    id: 'a1c-dogaspor-kamp',
    type: 'youtube',
    title: 'Kamp vlogu · İngilizce',
    where: 'YouTube — "camping vlog english" ara',
    levels: ['A1'],
    tastes: ['dogaspor', 'spor'],
    why: 'Doğa sporları seçtin. Kamp vloglarında eşyalar tek tek gösterilip adlandırılıyor; nesne kelimeleri için elverişli.',
    instruction: '10 dakikalık bir vlog izle. Gördüğün kamp eşyalarının adlarını yaz.',
    words: [
      { word: 'tent', meaning: 'çadır' },
      { word: 'fire', meaning: 'ateş' },
      { word: 'to cook', meaning: 'pişirmek' },
      { word: 'cold', meaning: 'soğuk' },
    ],
    watchFor: ['Kaç eşya adı öğrendin?', 'Havayı nasıl anlattı?'],
    noun: 'video',
  },

  /* ══════════════════════════════════════════════════ İLGİ ALANLARI */
  {
    id: 'a1c-oyun-inceleme',
    type: 'youtube',
    title: 'Oyun incelemesi · kısa ve basit',
    where: 'YouTube — sevdiğin oyunun adı + "review for beginners" ara',
    levels: ['A1'],
    tastes: ['oyun'],
    why: 'Oyun seçtin. İnceleme videolarında beğeni ve şikâyet cümleleri tekrarlanır — "I like…", "the problem is…" kalıpları A1\'de birebir işine yarar.',
    instruction: '10 dakikalık bir inceleme izle. Beğendiği ve beğenmediği şeyleri yaz.',
    words: [
      { word: 'I like', meaning: 'seviyorum' },
      { word: 'problem', meaning: 'sorun' },
      { word: 'easy / hard', meaning: 'kolay / zor' },
      { word: 'to try', meaning: 'denemek' },
    ],
    watchFor: ['Beğendiğini nasıl söylüyor?', 'Şikâyetini hangi kalıpla kuruyor?'],
    noun: 'video',
  },
  {
    id: 'a1c-teknoloji-uygulama',
    type: 'youtube',
    title: 'Uygulama tanıtımı · nasıl kullanılır',
    where: 'YouTube — "how to use [uygulama adı] tutorial" ara',
    levels: ['A1'],
    tastes: ['teknoloji'],
    why: 'Teknoloji seçtin. Kullanım anlatımları adım adım ilerler ve her adım ekranda gösterilir; "tap, open, choose" gibi günlük fiilleri öğreniyorsun.',
    instruction: 'Kullandığın bir uygulamanın anlatımını izle, 10 dakika. Adımları İngilizce yaz.',
    words: [
      { word: 'to tap', meaning: 'dokunmak' },
      { word: 'to choose', meaning: 'seçmek' },
      { word: 'settings', meaning: 'ayarlar' },
      { word: 'to save', meaning: 'kaydetmek' },
    ],
    watchFor: ['Kaç adım vardı?', 'Hangi emir fiilleri tekrarlandı?'],
    noun: 'video',
  },
  {
    id: 'a1c-yemek-sokak',
    type: 'youtube',
    title: 'Sokak yemeği videosu · İngilizce anlatım',
    where: 'YouTube — "street food english commentary" ara',
    levels: ['A1'],
    tastes: ['yemek'],
    why: 'Yemek seçtin. Sokak yemeği videolarında malzemeler tek tek gösterilip adlandırılıyor ve tat sıfatları sürekli tekrar ediyor.',
    instruction: '10 dakikalık bir video izle. Malzeme adlarını ve tat sıfatlarını yaz.',
    words: [
      { word: 'delicious', meaning: 'çok lezzetli' },
      { word: 'spicy', meaning: 'acılı' },
      { word: 'meat', meaning: 'et' },
      { word: 'bread', meaning: 'ekmek' },
    ],
    watchFor: ['Kaç tat sıfatı duydun?', 'Fiyat söylerken hangi kalıp geçiyor?'],
    noun: 'video',
  },
  {
    id: 'a1c-seyahat-sehirturu',
    type: 'youtube',
    title: 'Şehir turu videosu · yavaş anlatım',
    where: 'YouTube — "city walking tour with commentary" ara',
    levels: ['A1'],
    tastes: ['seyahat'],
    why: 'Seyahat seçtin. Yürüyüş turlarında anlatıcı gördüğünü anlatır ve tempo yavaştır; yer ve yön kelimeleri sürekli tekrar eder.',
    instruction: '10 dakika izle. Duyduğun yön kelimelerini ve yer adlarını yaz.',
    words: [
      { word: 'on the left', meaning: 'solda' },
      { word: 'square', meaning: 'meydan' },
      { word: 'building', meaning: 'bina' },
      { word: 'old', meaning: 'eski' },
    ],
    watchFor: ['Yön tarif ederken hangi kalıpları kullandı?', 'Kaç yapı adı geçti?'],
    noun: 'video',
  },
  {
    id: 'a1c-kitap-hikaye',
    type: 'youtube',
    title: 'Sesli kısa hikâye · yazıyla birlikte',
    where: 'YouTube — "short story english read along subtitles" ara',
    levels: ['A1'],
    tastes: ['kitap'],
    why: 'Kitap seçtin. Metni görerek dinlemek A1\'de en hızlı ilerleten yöntemlerden biri: duyduğun sesi yazıya bağlıyorsun.',
    instruction: '10 dakikalık bir hikâye dinle, metni gözle takip et. Sonra kendi cümlelerinle özetle.',
    words: [
      { word: 'once upon a time', meaning: 'bir zamanlar' },
      { word: 'to live', meaning: 'yaşamak' },
      { word: 'friend', meaning: 'arkadaş' },
      { word: 'at the end', meaning: 'sonunda' },
    ],
    watchFor: ['Hikâye hangi zamanda anlatılıyor?', 'Kaç yeni kelime yakaladın?'],
    noun: 'video',
  },
  {
    id: 'a1c-is-gorusme',
    type: 'youtube',
    title: 'İş görüşmesi · rol yapma videosu',
    where: 'YouTube — "job interview english role play beginner" ara',
    levels: ['A1'],
    tastes: ['is', 'ofis'],
    why: 'İş seçtin. Görüşme videolarında sorular sabittir ve tekrarlanır; kalıpları ezberlediğin an gerçek bir toplantıda kullanabilirsin.',
    instruction: 'Bir rol yapma videosu izle, 10 dakika. Soruları yaz ve kendi cevabını hazırla.',
    words: [
      { word: 'Tell me about yourself', meaning: 'Kendinden bahset' },
      { word: 'experience', meaning: 'deneyim' },
      { word: 'to work at', meaning: '…de çalışmak' },
      { word: 'strength', meaning: 'güçlü yön' },
    ],
    watchFor: ['Kaç soru soruldu?', 'Kendini tanıtırken hangi zamanı kullanıyor?'],
    noun: 'video',
  },
  {
    id: 'a1c-otomobil-nasil',
    type: 'youtube',
    title: 'Araba nasıl üretilir · fabrika videosu',
    where: 'YouTube — "how cars are made factory" ara',
    levels: ['A1'],
    tastes: ['otomobil'],
    why: 'Otomobil seçtin. Üretim videolarında her adım gösterilerek anlatılır; anlatım yavaş ve tekrarlıdır.',
    instruction: '10 dakikalık bir video izle. Üretim adımlarını sırayla yaz.',
    words: [
      { word: 'to build', meaning: 'üretmek, inşa etmek' },
      { word: 'metal', meaning: 'metal' },
      { word: 'part', meaning: 'parça' },
      { word: 'worker', meaning: 'işçi' },
    ],
    watchFor: ['Adımları sıralarken hangi kelimeleri kullandı?', 'Kaç parça adı geçti?'],
    noun: 'video',
  },
  {
    id: 'a1c-muzik-roportaj',
    type: 'youtube',
    title: 'Müzisyen röportajı · kısa',
    where: 'YouTube — sevdiğin sanatçının adı + "short interview" ara',
    levels: ['A1'],
    tastes: ['muzik'],
    why: 'Müzik seçtin. Röportajlarda sanatçı kendi hayatını anlatır: basit geçmiş zaman cümleleri ve tanıdık kelimeler.',
    instruction: '5-10 dakikalık bir röportaj izle. Anladığın cümleleri yaz.',
    words: [
      { word: 'to start', meaning: 'başlamak' },
      { word: 'band', meaning: 'grup' },
      { word: 'to write a song', meaning: 'şarkı yazmak' },
      { word: 'favourite', meaning: 'en sevdiği' },
    ],
    watchFor: ['Nasıl başladığını hangi zamanla anlattı?', 'Kaç soru soruldu?'],
    noun: 'video',
  },

  /* ═════════════════════════════════════════════════════ EKRAN TÜRÜ */
  {
    id: 'a1c-superhero-lego',
    type: 'series',
    title: 'LEGO süper kahraman kısa filmleri',
    where: 'YouTube — "LEGO superhero short film" ara',
    levels: ['A1'],
    tastes: ['superhero', 'dizi'],
    why: 'Süper kahraman seçtin. Bu kısa filmler 5 dakika, cümleler çok kısa ve espriler görsel — A1\'de rahat takip edilir.',
    instruction: 'İki kısa film izle. Karakterlerin birbirine söylediklerini not al.',
    words: [
      { word: 'to help', meaning: 'yardım etmek' },
      { word: 'bad guy', meaning: 'kötü adam' },
      { word: 'to catch', meaning: 'yakalamak' },
      { word: 'Let\'s go!', meaning: 'Hadi gidelim!' },
    ],
    watchFor: ['Kaç ünlem cümlesi duydun?', 'Kötü karakteri nasıl tarif ediyorlar?'],
    noun: 'episode',
  },
  {
    id: 'a1c-scifi-astro',
    type: 'youtube',
    title: 'Uzay istasyonu turu · astronot anlatımı',
    where: 'YouTube — "space station tour astronaut" ara',
    levels: ['A1'],
    tastes: ['scifi', 'dizi'],
    why: 'Bilim kurgu seçtin. Gerçek uzay videoları kurgudan daha yavaş konuşur ve her şey ekranda gösterilir — aynı dünya, anlaşılır dil.',
    instruction: '10 dakikalık bir tur izle. Gördüğün nesnelerin adlarını yaz.',
    words: [
      { word: 'space', meaning: 'uzay' },
      { word: 'to float', meaning: 'havada süzülmek' },
      { word: 'to sleep', meaning: 'uyumak' },
      { word: 'Earth', meaning: 'Dünya' },
    ],
    watchFor: ['Günlük işleri nasıl anlatıyor?', 'Kaç nesne adı öğrendin?'],
    noun: 'video',
  },
  {
    id: 'a1c-polisiye-bulmaca',
    type: 'youtube',
    title: 'Kısa dedektif bulmacası · İngilizce',
    where: 'YouTube — "short detective riddle english" ara',
    levels: ['A1'],
    tastes: ['polisiye', 'dizi'],
    why: 'Polisiye seçtin. Bulmaca videoları 3-5 dakika: olay basit cümlelerle anlatılıp soru soruluyor, sonra cevap veriliyor.',
    instruction: 'Bir bulmaca izle, cevabı duymadan durdur ve kendi cevabını İngilizce yaz.',
    words: [
      { word: 'to find', meaning: 'bulmak' },
      { word: 'who', meaning: 'kim' },
      { word: 'because', meaning: 'çünkü' },
      { word: 'answer', meaning: 'cevap' },
    ],
    watchFor: ['Olay hangi zamanda anlatılıyor?', 'Soru nasıl soruluyor?'],
    noun: 'video',
  },
  {
    id: 'a1c-komedi-mrbean',
    type: 'series',
    title: 'Mr. Bean · animasyon bölümleri',
    where: 'YouTube — "Mr Bean animated" ara',
    levels: ['A1'],
    tastes: ['komedi', 'dizi'],
    why: 'Komedi seçtin. Konuşma çok az, mizah tamamen görsel — anlamadığın için gülemediğin bir bölüm A1\'de moral bozar, bu risk burada yok.',
    instruction: 'Bir bölüm izle (10 dk). Sonra olayı İngilizce anlat — konuşma az olduğu için anlatan sen olacaksın.',
    words: [
      { word: 'to forget', meaning: 'unutmak' },
      { word: 'to be late', meaning: 'geç kalmak' },
      { word: 'funny', meaning: 'komik' },
      { word: 'to fall', meaning: 'düşmek' },
    ],
    watchFor: ['Olayı kaç cümleyle anlatabildin?', 'Hangi fiiller gerekti?'],
    noun: 'episode',
  },
  {
    id: 'a1c-dram-kisa',
    type: 'youtube',
    title: 'Kısa animasyon filmi · duygusal',
    where: 'YouTube — "short animated film" ara (Pixar kısa filmleri gibi)',
    levels: ['A1'],
    tastes: ['dram', 'dizi'],
    why: 'Dram seçtin. Kısa animasyonlarda konuşma neredeyse yok; hikâyeyi anlatan sen olacaksın, bu da A1\'de en çok geliştiren alıştırma.',
    instruction: '5 dakikalık bir kısa film izle. Hikâyeyi 5 cümleyle İngilizce anlat.',
    words: [
      { word: 'to feel', meaning: 'hissetmek' },
      { word: 'alone', meaning: 'yalnız' },
      { word: 'to help', meaning: 'yardım etmek' },
      { word: 'happy end', meaning: 'mutlu son' },
    ],
    watchFor: ['Hikâyeyi kaç cümleyle anlattın?', 'Hangi duygu kelimeleri gerekti?'],
    noun: 'film',
  },
  {
    id: 'a1c-gerilim-goosebumps',
    type: 'series',
    title: 'Goosebumps · çocuklar için korku dizisi',
    where: 'Netflix / YouTube — "Goosebumps episode" ara',
    levels: ['A1'],
    tastes: ['gerilim', 'dizi'],
    why: 'Gerilim seçtin. Bu dizi çocuklar için çekildiği için cümleler kısa, ama havası gerçekten gerilimli — A1\'de tempoyu kaybetmezsin.',
    instruction: 'Bir bölüm izle, 20 dakika. Korku anlatan kelimeleri topla.',
    words: [
      { word: 'scary', meaning: 'korkutucu' },
      { word: 'to scream', meaning: 'çığlık atmak' },
      { word: 'dark', meaning: 'karanlık' },
      { word: 'strange', meaning: 'tuhaf' },
    ],
    watchFor: ['Kaç korku sıfatı duydun?', 'Karakterler korktuklarını nasıl söylüyor?'],
    noun: 'episode',
  },
  {
    id: 'a1c-animasyon-pocoyo',
    type: 'series',
    title: 'Pocoyo · çok kısa bölümler',
    where: 'YouTube — "Pocoyo english" ara',
    levels: ['A1'],
    tastes: ['animasyon', 'dizi'],
    why: 'Animasyon seçtin. Bölümler 5-7 dakika ve anlatıcı tek tek, çok yavaş konuşuyor — İngilizceye ilk günlerinde bile takip edilir.',
    instruction: 'İki bölüm izle. Anlatıcının kullandığı emir ve soru cümlelerini yaz.',
    words: [
      { word: 'Look!', meaning: 'Bak!' },
      { word: 'What is this?', meaning: 'Bu ne?' },
      { word: 'to jump', meaning: 'zıplamak' },
      { word: 'colour', meaning: 'renk' },
    ],
    watchFor: ['Anlatıcı kaç soru sordu?', 'Kaç renk adı geçti?'],
    noun: 'episode',
  },
  {
    id: 'a1c-fantastik-masal',
    type: 'youtube',
    title: 'İngilizce masal anlatımı · animasyonlu',
    where: 'YouTube — "fairy tales in english animated" ara',
    levels: ['A1'],
    tastes: ['fantastik', 'dizi'],
    why: 'Fantastik seçtin. Masallar bilerek yavaş anlatılır ve olay örgüsünü zaten biliyorsun; bilinen bir hikâyeyi İngilizce dinlemek A1\'de en kolay yoldur.',
    instruction: 'Bildiğin bir masalı İngilizce izle, 10 dakika. Tanıdığın kelimeleri işaretle.',
    words: [
      { word: 'king', meaning: 'kral' },
      { word: 'forest', meaning: 'orman' },
      { word: 'to save', meaning: 'kurtarmak' },
      { word: 'magic', meaning: 'sihir' },
    ],
    watchFor: ['Hikâye hangi zamanda anlatılıyor?', 'Kaç kelimeyi zaten biliyordun?'],
    noun: 'video',
  },
  {
    id: 'a1c-tarihi-belgesel',
    type: 'youtube',
    title: 'Antik dünya · kısa animasyonlu anlatım',
    where: 'YouTube — "ancient history animated short english" ara',
    levels: ['A1'],
    tastes: ['tarihi', 'dizi'],
    why: 'Tarihi yapımlar seçtin. Animasyonlu tarih anlatımları 5 dakika ve görselle desteklendiği için A1\'de takip edilebilir.',
    instruction: 'Bir video izle. Geçen yer ve halk adlarını yaz.',
    words: [
      { word: 'ancient', meaning: 'antik' },
      { word: 'city', meaning: 'şehir' },
      { word: 'to build', meaning: 'inşa etmek' },
      { word: 'people', meaning: 'halk, insanlar' },
    ],
    watchFor: ['Kaç yer adı geçti?', 'Geçmiş zaman fiillerini yakaladın mı?'],
    noun: 'video',
  },

  /* ═══════════════════════════════════════════════ KULLANIM ORTAMI */
  {
    id: 'a1c-gunluk-kalip',
    type: 'youtube',
    title: 'Günlük İngilizce kalıplar · tekrarlı ders',
    where: 'YouTube — "daily english phrases for beginners" ara',
    levels: ['A1'],
    tastes: ['gunluk'],
    why: 'Günlük hayat ortamını seçtin. Bu videolar kalıbı söyleyip tekrar ettiriyor; sesli tekrar A1\'de telaffuzu da birlikte oturtuyor.',
    instruction: 'Bir video izle ve **sesli tekrar et**. Öğrendiğin 5 kalıbı yaz.',
    words: [
      { word: 'How are you?', meaning: 'Nasılsın?' },
      { word: 'See you later', meaning: 'Sonra görüşürüz' },
      { word: 'Excuse me', meaning: 'Affedersiniz' },
      { word: 'Thank you', meaning: 'Teşekkürler' },
    ],
    watchFor: ['Kaç kalıp ezberledin?', 'Hangileri bugün işine yarar?'],
    noun: 'video',
  },
  {
    id: 'a1c-seyahat-otel',
    type: 'youtube',
    title: 'Otel ve restoran konuşmaları · rol yapma',
    where: 'YouTube — "hotel and restaurant english conversation" ara',
    levels: ['A1'],
    tastes: ['seyahat-ortam'],
    why: 'Seyahat ortamını seçtin. Otel ve restoran diyalogları sabittir; ezberlediğin an gerçekten kullanırsın.',
    instruction: 'Bir video izle, kalıpları sesli tekrar et. Kendi cümlelerini kur.',
    words: [
      { word: 'I would like…', meaning: '… istiyorum' },
      { word: 'bill / check', meaning: 'hesap' },
      { word: 'room', meaning: 'oda' },
      { word: 'How much?', meaning: 'Ne kadar?' },
    ],
    watchFor: ['Sipariş verirken hangi kalıp kullanılıyor?', 'Görevli nasıl karşılıyor?'],
    noun: 'video',
  },
  {
    id: 'a1c-sosyal-yorum',
    type: 'youtube',
    title: 'İnternet yorumları ve kısaltmalar · İngilizce',
    where: 'YouTube — "english internet slang for beginners" ara',
    levels: ['A1'],
    tastes: ['sosyal'],
    why: 'Sosyal medya ortamını seçtin. İnternette gördüğün kısaltmaların ne demek olduğunu öğrenmek, yazışmalarda anlamadığın kısmı doğrudan kapatıyor.',
    instruction: 'Bir video izle, 10 dakika. Öğrendiğin kısaltmaları anlamlarıyla yaz.',
    words: [
      { word: 'btw', meaning: 'bu arada' },
      { word: 'imo', meaning: 'bence' },
      { word: 'lol', meaning: 'gülme ifadesi' },
      { word: 'asap', meaning: 'en kısa sürede' },
    ],
    watchFor: ['Kaç kısaltma öğrendin?', 'Hangileri resmi yazışmada kullanılmaz?'],
    noun: 'video',
  },
  {
    id: 'a1c-akademik-ders',
    type: 'youtube',
    title: 'Temel matematik anlatımı · İngilizce',
    where: 'YouTube — "basic math in english for beginners" ara',
    levels: ['A1'],
    tastes: ['akademik'],
    why: 'Akademik metin seçtin. Matematik anlatımı A1\'de iyi bir başlangıç: konuyu zaten biliyorsun, öğrendiğin tek şey İngilizcesi oluyor.',
    instruction: 'Bir ders izle, 10 dakika. Sayı ve işlem adlarını yaz.',
    words: [
      { word: 'plus / minus', meaning: 'artı / eksi' },
      { word: 'equals', meaning: 'eşittir' },
      { word: 'to divide', meaning: 'bölmek' },
      { word: 'number', meaning: 'sayı' },
    ],
    watchFor: ['İşlemleri nasıl okuyor?', 'Kaç sayı adı yakaladın?'],
    noun: 'video',
  },
];
