/**
 * A1 fazı — **müzik havuzu.**
 *
 * Kullanıcının bildirimi: *"sürekli tek müzik geliyor, bunu değiştirelim."*
 * `a1.ts` her türe birer şarkı koyuyordu; kapsam tamdı ama tür seçen kişi
 * hep aynı parçayı görüyordu.
 *
 * ## A1'de bir şarkı neye göre seçilir
 *
 * Tür beğenisi tek başına yetmiyor — metal seven bir A1 öğrencisine bağırarak
 * söylenen bir parça vermek dinleme çalışması olmaz, moral bozar. Ölçüt üç
 * madde:
 *
 *   1. **Tempo yavaş**, sözler arasında boşluk var
 *   2. **Telaffuz net** — kelimeler birbirine yapışmıyor
 *   3. **Sözler tekrarlı ve somut** — soyut şiir değil, günlük kelimeler
 *
 * Bu yüzden her tür, o türün *en sakin* parçalarıyla temsil ediliyor ve
 * gerekçede bu açıkça söyleniyor. Kullanıcı neden o parçayı aldığını bilmeli;
 * "metal seviyorsun al sana metal" demek yerine "metal seviyorsun ama A1'de
 * şu sebeple bu parça" demek hem dürüst hem öğretici.
 *
 * ⚠️ **Şarkı sözü kopyalanmıyor.** Telifli metin bu depoya girmez; yalnızca
 * parçanın adı, neden seçildiği ve neye dikkat edileceği yazılıyor. Sözleri
 * kullanıcı kendi servisinde görüyor.
 */

import type { CatalogItem } from './types';

/** Tekrar tekrar yazmamak için — hepsi tek seviyeye ait */
const A1 = ['A1'] as const;

export const A1_MUZIK: CatalogItem[

] = [
  /* ═══════════════════════════════════════════════════════════ ROCK */
  {
    id: 'a1m-rock-ccr',
    type: 'song',
    title: 'Creedence Clearwater Revival — Have You Ever Seen the Rain',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['rock'],
    why: 'Rock seçtin. Tempo orta, telaffuz çok net ve nakarat bir soru cümlesi — soru kalıbı çalışmak için elverişli.',
    instruction: 'Önce sözsüz dinle, nakaratı yakalamaya çalış. Sonra sözleriyle kontrol et.',
    words: [
      { word: 'rain', meaning: 'yağmur' },
      { word: 'sunny', meaning: 'güneşli' },
      { word: 'to come down', meaning: 'inmek, yağmak' },
      { word: 'Have you ever…?', meaning: 'Hiç … yaptın mı?' },
    ],
    watchFor: ['Nakarattaki soru nasıl kuruluyor?', '"rain" kaç kez geçiyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-rock-adams',
    type: 'song',
    title: 'Bryan Adams — Summer of \'69',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['rock'],
    why: 'Rock seçtin. Bu parça baştan sona geçmiş zamanla bir hikâye anlatıyor; A1\'de geçmiş zamanı şarkıyla duymak kitaptan hızlı oturuyor.',
    instruction: 'Sözleriyle dinle ve geçmiş zaman fiillerini işaretle. En az 5 tane bulacaksın.',
    words: [
      { word: 'summer', meaning: 'yaz' },
      { word: 'to buy', meaning: 'satın almak' },
      { word: 'to play', meaning: 'çalmak, oynamak' },
      { word: 'best days', meaning: 'en güzel günler' },
    ],
    watchFor: ['Kaç geçmiş zaman fiili buldun?', 'Hikâye kim hakkında?'],
    noun: 'song',
  },
  {
    id: 'a1m-rock-petty',
    type: 'song',
    title: 'Tom Petty — Free Fallin\'',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['rock'],
    why: 'Rock seçtin. Yavaş, sakin ve dizeler kısa; aynı kalıp defalarca tekrar ettiği için ezberlemesi kolay.',
    instruction: 'Önce sözsüz dinle. Tekrar eden dizeyi yakalayıp birlikte söylemeyi dene.',
    words: [
      { word: 'to love', meaning: 'sevmek' },
      { word: 'good girl / boy', meaning: 'iyi kız / oğlan' },
      { word: 'town', meaning: 'kasaba' },
      { word: 'to fall', meaning: 'düşmek' },
    ],
    watchFor: ['En çok tekrar eden dize hangisi?', '"she" ile başlayan kaç cümle var?'],
    noun: 'song',
  },

  /* ══════════════════════════════════════════════════════════ METAL */
  {
    id: 'a1m-metal-unforgiven',
    type: 'song',
    title: 'Metallica — The Unforgiven',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['metal'],
    why: 'Metal seçtin. Bu parça sert değil, anlatı gibi söyleniyor ve kelimeler tek tek duyuluyor — metalde A1\'e uyan az sayıda parçadan biri.',
    instruction: 'Önce sözsüz dinle, sonra sözleriyle. Anladığın 5 kelimeyi yaz.',
    words: [
      { word: 'young', meaning: 'genç' },
      { word: 'to fight', meaning: 'savaşmak' },
      { word: 'life', meaning: 'hayat' },
      { word: 'never', meaning: 'asla' },
    ],
    watchFor: ['"never" kaç kez geçiyor?', 'Şarkı kimin hikâyesini anlatıyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-metal-scorpions',
    type: 'song',
    title: 'Scorpions — Wind of Change',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['metal', 'rock'],
    why: 'Metal/rock seçtin. Bu bir balat: çok yavaş, telaffuz kusursuz net ve sözler somut — A1\'de ilk baştan sona anlayabileceğin parçalardan biri.',
    instruction: 'Sözsüz dinle ve kaç kelime yakaladığını say. Sonra sözleriyle karşılaştır.',
    words: [
      { word: 'wind', meaning: 'rüzgâr' },
      { word: 'change', meaning: 'değişim' },
      { word: 'future', meaning: 'gelecek' },
      { word: 'to follow', meaning: 'takip etmek' },
    ],
    watchFor: ['Sözsüz kaç kelime yakaladın?', '"change" hangi anlamda kullanılıyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-metal-sabbath',
    type: 'song',
    title: 'Black Sabbath — Changes',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['metal'],
    why: 'Metal seçtin. Bu parça piyanolu ve çok yavaş; sözleri kısa cümlelerden oluşuyor, metal grubundan gelen en A1 dostu şarkılardan.',
    instruction: 'Sözleriyle dinle. Cümlelerin ne kadar kısa olduğuna dikkat et; birkaçını ezberle.',
    words: [
      { word: 'to change', meaning: 'değişmek' },
      { word: 'to feel', meaning: 'hissetmek' },
      { word: 'sad', meaning: 'üzgün' },
      { word: 'to go through', meaning: 'yaşamak, geçirmek' },
    ],
    watchFor: ['En uzun cümle kaç kelime?', '"I feel" kaç kez geçiyor?'],
    noun: 'song',
  },

  /* ════════════════════════════════════════════════════════════ POP */
  {
    id: 'a1m-pop-brunomars',
    type: 'song',
    title: 'Bruno Mars — Count on Me',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['pop'],
    why: 'Pop seçtin. Bu parça neredeyse bir A1 ders kitabı: geniş zaman, basit cümleler, arkadaşlık üzerine somut kelimeler.',
    instruction: 'Sözleriyle dinle ve nakaratı ezberle. Sonra kendi cümlelerini kurmayı dene.',
    words: [
      { word: 'to count on', meaning: 'güvenmek, bel bağlamak' },
      { word: 'friend', meaning: 'arkadaş' },
      { word: 'to find', meaning: 'bulmak' },
      { word: 'to help', meaning: 'yardım etmek' },
    ],
    watchFor: ['Şart cümlesi ("if…") var mı?', 'Kaç fiil geniş zamanda?'],
    noun: 'song',
  },
  {
    id: 'a1m-pop-adele',
    type: 'song',
    title: 'Adele — Someone Like You',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['pop'],
    why: 'Pop seçtin. Sadece piyano ve ses var; arkada gürültü olmadığı için her kelime ayrı ayrı duyuluyor — dinleme çalışması için ideal.',
    instruction: 'Önce sözsüz dinle, kaç kelime yakaladığını yaz. Sonra sözleriyle karşılaştır.',
    words: [
      { word: 'to find', meaning: 'bulmak' },
      { word: 'to remember', meaning: 'hatırlamak' },
      { word: 'to wish', meaning: 'dilemek' },
      { word: 'nothing', meaning: 'hiçbir şey' },
    ],
    watchFor: ['Sözsüz kaç kelime yakaladın?', 'Şarkı hangi zamanda anlatılıyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-pop-perfect',
    type: 'song',
    title: 'Ed Sheeran — Perfect',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['pop'],
    why: 'Pop seçtin. Yavaş ve hikâye gibi ilerliyor; sözlerin çoğu somut kelimelerden oluşuyor ve tekrar eden bölümü kısa.',
    instruction: 'Sözleriyle dinle. Sıfatları topla, en az 4 tane.',
    words: [
      { word: 'perfect', meaning: 'mükemmel' },
      { word: 'to dance', meaning: 'dans etmek' },
      { word: 'to hold', meaning: 'tutmak' },
      { word: 'darling', meaning: 'sevgilim' },
    ],
    watchFor: ['Kaç sıfat buldun?', 'Nakarat kaç kez tekrarlanıyor?'],
    noun: 'song',
  },

  /* ════════════════════════════════════════════════════════════ RAP */
  {
    id: 'a1m-rap-sugarhill',
    type: 'song',
    title: 'The Sugarhill Gang — Rapper\'s Delight',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['rap'],
    why: 'Rap seçtin. Eski okul rap bugünkünden çok daha yavaş; kelimeler tek tek söyleniyor, bu yüzden A1\'de rap dinlemenin en kolay yolu.',
    instruction: 'İlk kıtayı sözleriyle takip et. Ritmi tutturarak birlikte söylemeyi dene.',
    words: [
      { word: 'to say', meaning: 'söylemek' },
      { word: 'party', meaning: 'parti, eğlence' },
      { word: 'friend', meaning: 'arkadaş' },
      { word: 'to move', meaning: 'hareket etmek' },
    ],
    watchFor: ['İlk kıtada kaç kelime anladın?', 'Tekrar eden bölüm hangisi?'],
    noun: 'song',
  },
  {
    id: 'a1m-rap-nelly',
    type: 'song',
    title: 'Nelly — Just a Dream',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['rap'],
    why: 'Rap seçtin. Nakaratı söylenerek (rap edilmeden) geliyor ve çok tekrarlı; A1\'de önce nakaratı, sonra kıtaları çözersin.',
    instruction: 'Sadece nakarata odaklan; onu ezberle. Kıtaları anlamaya çalışma, henüz erken.',
    words: [
      { word: 'dream', meaning: 'rüya' },
      { word: 'to think', meaning: 'düşünmek' },
      { word: 'to wake up', meaning: 'uyanmak' },
      { word: 'gone', meaning: 'gitmiş' },
    ],
    watchFor: ['Nakaratta kaç kelime var?', '"dream" kaç kez geçiyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-rap-notafraid',
    type: 'song',
    title: 'Eminem — Not Afraid (sadece nakarat)',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['rap'],
    why: 'Rap seçtin. Kıtaları A1 için çok hızlı — ama nakaratı yavaş ve net söyleniyor. Bilerek yarısını çalışıyoruz; tamamını anlamak B1 işi.',
    instruction: '**Sadece nakaratı** çalış: sözleriyle iki kez dinle ve ezberle. Kıtalara takılma.',
    words: [
      { word: 'afraid', meaning: 'korkmuş' },
      { word: 'to stand up', meaning: 'ayağa kalkmak' },
      { word: 'alone', meaning: 'yalnız' },
      { word: 'anymore', meaning: 'artık' },
    ],
    watchFor: ['Nakaratı ezberleyebildin mi?', '"not afraid" ne demek?'],
    noun: 'song',
  },

  /* ══════════════════════════════════════════════════════ ELEKTRONİK */
  {
    id: 'a1m-elektronik-faded',
    type: 'song',
    title: 'Alan Walker — Faded',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['elektronik'],
    why: 'Elektronik seçtin. Sözleri az ve aynı dizeler sürekli dönüyor; az kelimeyi çok kez duymak A1\'de en iyi öğretme biçimi.',
    instruction: 'Sözsüz dinle ve tekrar eden dizeyi yakala. Sonra sözleriyle kontrol et.',
    words: [
      { word: 'lost', meaning: 'kaybolmuş' },
      { word: 'where are you', meaning: 'neredesin' },
      { word: 'to find', meaning: 'bulmak' },
      { word: 'faded', meaning: 'solmuş, silikleşmiş' },
    ],
    watchFor: ['Tekrar eden dize hangisi?', 'Kaç soru cümlesi var?'],
    noun: 'song',
  },
  {
    id: 'a1m-elektronik-firestone',
    type: 'song',
    title: 'Kygo — Firestone',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['elektronik'],
    why: 'Elektronik seçtin. Vokal yavaş ve arkadaki müzik sakin; sözler kısa cümlelerden oluşuyor.',
    instruction: 'Önce sözsüz dinle, sonra sözleriyle. Anladığın kelimeleri işaretle.',
    words: [
      { word: 'fire', meaning: 'ateş' },
      { word: 'to burn', meaning: 'yanmak' },
      { word: 'heart', meaning: 'kalp' },
      { word: 'to hold on', meaning: 'tutunmak' },
    ],
    watchFor: ['Nakarat kaç kez geçiyor?', 'Kaç kelime tanıdık geldi?'],
    noun: 'song',
  },
  {
    id: 'a1m-elektronik-titanium',
    type: 'song',
    title: 'David Guetta & Sia — Titanium',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['elektronik', 'pop'],
    why: 'Elektronik seçtin. Nakarat güçlü ve çok net söyleniyor; kelimeler uzatılarak okunduğu için takip etmesi kolay.',
    instruction: 'Nakarata odaklan ve ezberle. Sonra tamamını sözleriyle dinle.',
    words: [
      { word: 'strong', meaning: 'güçlü' },
      { word: 'to shoot', meaning: 'ateş etmek' },
      { word: 'to fall down', meaning: 'yere düşmek' },
      { word: 'bulletproof', meaning: 'kurşun geçirmez' },
    ],
    watchFor: ['Nakaratta hangi kelime uzatılıyor?', 'Şarkı ne anlatıyor?'],
    noun: 'song',
  },

  /* ════════════════════════════════════════════════════════════ CAZ */
  {
    id: 'a1m-caz-love',
    type: 'song',
    title: 'Nat King Cole — L-O-V-E',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['caz'],
    why: 'Caz seçtin. Şarkı kelimenin harflerini tek tek söyleyip her harfi bir cümleyle açıklıyor — A1 için hazırlanmış gibi bir yapı.',
    instruction: 'Sözleriyle dinle. Her harfin hangi kelimeyle açıklandığını yaz.',
    words: [
      { word: 'love', meaning: 'aşk, sevgi' },
      { word: 'more than', meaning: '…den daha çok' },
      { word: 'to look at', meaning: 'bakmak' },
      { word: 'two', meaning: 'iki' },
    ],
    watchFor: ['Her harf hangi kelimeyi açıyor?', 'Kaç sıfat geçiyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-caz-ella',
    type: 'song',
    title: 'Ella Fitzgerald — Summertime',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['caz'],
    why: 'Caz seçtin. Çok yavaş ve sözleri az; her dize arasında boşluk olduğu için kelimeleri ayırt etmek kolay.',
    instruction: 'Sözsüz dinle, duyduğun kelimeleri yaz. Sonra sözleriyle karşılaştır.',
    words: [
      { word: 'summertime', meaning: 'yaz zamanı' },
      { word: 'easy', meaning: 'kolay' },
      { word: 'fish', meaning: 'balık' },
      { word: 'to jump', meaning: 'zıplamak' },
    ],
    watchFor: ['Kaç kelime yakaladın?', 'Şarkı hangi mevsimi anlatıyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-caz-buble',
    type: 'song',
    title: 'Michael Bublé — Everything',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['caz'],
    why: 'Caz seçtin. Modern ve neşeli; sözler "you are my…" kalıbı üzerine kurulu, yani tek bir yapıyı defalarca duyuyorsun.',
    instruction: 'Sözleriyle dinle. "You are my…" kalıbının kaç kez geçtiğini say.',
    words: [
      { word: 'everything', meaning: 'her şey' },
      { word: 'to need', meaning: 'ihtiyaç duymak' },
      { word: 'sunshine', meaning: 'güneş ışığı' },
      { word: 'to smile', meaning: 'gülümsemek' },
    ],
    watchFor: ['Kalıp kaç kez geçiyor?', 'Kaç isim sayıyor?'],
    noun: 'song',
  },

  /* ══════════════════════════════════════════════════════════ BLUES */
  {
    id: 'a1m-blues-raycharles',
    type: 'song',
    title: 'Ray Charles — Hit the Road Jack',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['blues'],
    why: 'Blues seçtin. Şarkı neredeyse tamamen tek bir cümlenin tekrarı; kısa, hızlı öğrenilir ve iki kişi arasında geçen bir konuşma gibi.',
    instruction: 'Sözleriyle dinle. Tekrar eden cümleyi ezberle ve birlikte söyle.',
    words: [
      { word: 'road', meaning: 'yol' },
      { word: 'to come back', meaning: 'geri dönmek' },
      { word: 'no more', meaning: 'artık değil' },
      { word: 'to hit the road', meaning: 'yola koyulmak, çekip gitmek' },
    ],
    watchFor: ['Tekrar eden cümle kaç kez geçiyor?', 'Kim kime söylüyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-blues-bbking',
    type: 'song',
    title: 'B.B. King — The Thrill Is Gone',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['blues'],
    why: 'Blues seçtin. Sözler seyrek: uzun müzik bölümleri arasında kısa cümleler var, bu da her cümleyi ayrı ayrı çalışmanı sağlıyor.',
    instruction: 'Sözleriyle dinle ve her cümleyi durdurup tekrar et.',
    words: [
      { word: 'gone', meaning: 'gitmiş' },
      { word: 'to stay', meaning: 'kalmak' },
      { word: 'free', meaning: 'özgür' },
      { word: 'wrong', meaning: 'yanlış' },
    ],
    watchFor: ['Kaç cümle var, sayabildin mi?', 'Şarkı neyi anlatıyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-blues-clapton',
    type: 'song',
    title: 'Eric Clapton — Wonderful Tonight',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['blues', 'akustik'],
    why: 'Blues seçtin. Bu parça bir akşamı adım adım anlatıyor: giyinmek, çıkmak, dönmek — günlük fiillerin hepsi bir arada.',
    instruction: 'Sözleriyle dinle. Akşamın adımlarını sırayla yaz.',
    words: [
      { word: 'tonight', meaning: 'bu gece' },
      { word: 'to wear', meaning: 'giymek' },
      { word: 'to feel', meaning: 'hissetmek' },
      { word: 'wonderful', meaning: 'harika' },
    ],
    watchFor: ['Kaç günlük fiil geçiyor?', 'Olaylar hangi sırayla anlatılıyor?'],
    noun: 'song',
  },

  /* ════════════════════════════════════════════════════════════ KLASİK */
  {
    id: 'a1m-klasik-edelweiss',
    type: 'song',
    title: 'Edelweiss (The Sound of Music)',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['klasik'],
    why: 'Klasik seçtin. Enstrümantal parçalarda söz olmadığı için dinleme çalışması olmaz; bu orkestralı parça çok yavaş ve sözleri sekiz-on kelimeden ibaret.',
    instruction: 'Sözleriyle dinle ve tamamını ezberlemeyi dene — bu kadar kısa bir şarkıyı A1\'de bitirebilirsin.',
    words: [
      { word: 'small', meaning: 'küçük' },
      { word: 'white', meaning: 'beyaz' },
      { word: 'clean', meaning: 'temiz' },
      { word: 'to bloom', meaning: 'çiçek açmak' },
    ],
    watchFor: ['Kaç sıfat var?', 'Şarkının tamamını ezberleyebildin mi?'],
    noun: 'song',
  },
  {
    id: 'a1m-klasik-doremi',
    type: 'song',
    title: 'Do-Re-Mi (The Sound of Music)',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['klasik'],
    why: 'Klasik seçtin. Bu parça her notayı bir kelimeyle eşleştirerek ilerliyor; kelime-ses eşleştirmesi A1\'de tam olarak çalışman gereken şey.',
    instruction: 'Sözleriyle dinle. Her notanın hangi kelimeyle eşleştiğini yaz.',
    words: [
      { word: 'deer', meaning: 'geyik' },
      { word: 'drop', meaning: 'damla' },
      { word: 'sun', meaning: 'güneş' },
      { word: 'needle', meaning: 'iğne' },
    ],
    watchFor: ['Kaç nota-kelime eşleşmesi var?', 'Hangi kelimeler yeni?'],
    noun: 'song',
  },
  {
    id: 'a1m-klasik-favorite',
    type: 'song',
    title: 'My Favorite Things (The Sound of Music)',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['klasik'],
    why: 'Klasik seçtin. Şarkı baştan sona bir nesne listesi — A1\'de isim dağarcığını genişletmek için şarkı formatındaki en verimli parçalardan biri.',
    instruction: 'Sözleriyle dinle ve geçen nesneleri listele. Sonra kendi listeni İngilizce yaz.',
    words: [
      { word: 'favourite', meaning: 'en sevdiği' },
      { word: 'thing', meaning: 'şey' },
      { word: 'kitten', meaning: 'kedi yavrusu' },
      { word: 'package', meaning: 'paket' },
    ],
    watchFor: ['Kaç nesne saydın?', 'Kaçının anlamını bilmiyordun?'],
    noun: 'song',
  },

  /* ══════════════════════════════════════════════════════════ COUNTRY */
  {
    id: 'a1m-country-ringoffire',
    type: 'song',
    title: 'Johnny Cash — Ring of Fire',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['country'],
    why: 'Country seçtin. Şarkı iki buçuk dakika, sözleri az ve nakarat sürekli tekrar ediyor; telaffuz da çok belirgin.',
    instruction: 'Sözleriyle dinle, nakaratı ezberle ve birlikte söyle.',
    words: [
      { word: 'ring', meaning: 'halka, çember' },
      { word: 'fire', meaning: 'ateş' },
      { word: 'to burn', meaning: 'yanmak' },
      { word: 'to fall', meaning: 'düşmek' },
    ],
    watchFor: ['Nakarat kaç kez geçiyor?', '"ring of fire" ne anlatıyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-country-jolene',
    type: 'song',
    title: 'Dolly Parton — Jolene',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['country'],
    why: 'Country seçtin. Bir isim defalarca tekrarlanıyor ve şarkı doğrudan birine seslenerek ilerliyor; rica kalıpları için iyi bir örnek.',
    instruction: 'Sözleriyle dinle. Şarkıcının Jolene\'den ne istediğini İngilizce tek cümleyle yaz.',
    words: [
      { word: 'please', meaning: 'lütfen' },
      { word: 'to take', meaning: 'almak' },
      { word: 'beautiful', meaning: 'güzel' },
      { word: 'man', meaning: 'adam' },
    ],
    watchFor: ['"Jolene" kaç kez geçiyor?', 'Rica nasıl kuruluyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-country-walktheline',
    type: 'song',
    title: 'Johnny Cash — I Walk the Line',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['country'],
    why: 'Country seçtin. Yavaş, kısa ve her kıta aynı yapıda; aynı cümle kalıbını farklı kelimelerle duymak A1\'de kalıbı oturtuyor.',
    instruction: 'Sözleriyle dinle. Tekrar eden cümle yapısını bulup kendi cümleni kur.',
    words: [
      { word: 'to walk', meaning: 'yürümek' },
      { word: 'line', meaning: 'çizgi' },
      { word: 'to keep', meaning: 'sürdürmek, tutmak' },
      { word: 'true', meaning: 'sadık, doğru' },
    ],
    watchFor: ['Tekrar eden yapı hangisi?', 'Kaç kıta var?'],
    noun: 'song',
  },

  /* ═════════════════════════════════════════════════════════ AKUSTİK */
  {
    id: 'a1m-akustik-mraz',
    type: 'song',
    title: 'Jason Mraz — I\'m Yours',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['akustik'],
    why: 'Akustik seçtin. Tek gitar ve ses; tempo rahat, sözler günlük konuşma diline yakın ve nakarat çok kısa.',
    instruction: 'Nakaratı ezberle ve birlikte söyle. Sonra tamamını sözleriyle dinle.',
    words: [
      { word: 'to open', meaning: 'açmak' },
      { word: 'mind', meaning: 'zihin, akıl' },
      { word: 'to wait', meaning: 'beklemek' },
      { word: 'yours', meaning: 'senin' },
    ],
    watchFor: ['Nakarat kaç kelime?', '"I\'m yours" ne demek?'],
    noun: 'song',
  },
  {
    id: 'a1m-akustik-iz',
    type: 'song',
    title: 'Israel Kamakawiwoʻole — Over the Rainbow',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['akustik'],
    why: 'Akustik seçtin. Ukulele ile çok sakin bir düzenleme; sözler yavaş ve tanıdık, çoğu kişi melodiyi zaten biliyor.',
    instruction: 'Sözsüz dinle, tanıdığın kelimeleri yaz. Sonra sözleriyle karşılaştır.',
    words: [
      { word: 'rainbow', meaning: 'gökkuşağı' },
      { word: 'dream', meaning: 'rüya' },
      { word: 'sky', meaning: 'gökyüzü' },
      { word: 'to come true', meaning: 'gerçekleşmek' },
    ],
    watchFor: ['Kaç kelime yakaladın?', 'Şarkı neyi hayal ediyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-akustik-passenger',
    type: 'song',
    title: 'Passenger — Let Her Go',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['akustik'],
    why: 'Akustik seçtin. Nakarat "only … when …" kalıbı üzerine kurulu ve defalarca tekrar ediyor; tek bir yapıyı bolca duyuyorsun.',
    instruction: 'Sözleriyle dinle. Nakarattaki kalıbı bulup kendi cümlelerini kur.',
    words: [
      { word: 'to miss', meaning: 'özlemek' },
      { word: 'light', meaning: 'ışık' },
      { word: 'low', meaning: 'alçak, düşük' },
      { word: 'to let go', meaning: 'bırakmak' },
    ],
    watchFor: ['Nakarattaki kalıp nedir?', 'Kaç kez tekrar ediyor?'],
    noun: 'song',
  },

  /* ══════════════════ İKİNCİ TUR — sanatçı çeşitliliği ══════════════════
   *
   * Kullanıcının bildirimi: *"adam müziğe girdi, Bruno Mars geldi; yarın
   * geldi yine Bruno Mars'a gelmesin, Katy Perry, X sanatçı."*
   *
   * İki değişiklik birlikte çalışıyor. Seçim artık gün gün **sırayla**
   * yürüyor (`pickBest`, `gunSirasi`) — ama sıranın işe yaraması için
   * havuzun derin olması gerekiyor: tür başına 2-3 parça varken sıra iki
   * günde bir başa dönüyordu. Bu blok her türü **farklı sanatçılarla**
   * büyütüyor; artık aynı sanatçı bir hafta içinde geri gelmiyor.
   */
  {
    id: 'a1m-rock-beatles',
    type: 'song',
    title: 'The Beatles — Let It Be',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['rock'],
    why: 'Rock seçtin. Tempo yavaş, telaffuz çok net ve nakarat tek bir kalıptan ibaret.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'to let', meaning: 'bırakmak' },
      { word: 'word', meaning: 'kelime' },
      { word: 'hour', meaning: 'saat' },
      { word: 'to be', meaning: 'olmak' },
    ],
    watchFor: ['Nakarat kaç kez tekrar ediyor?', '"let it be" ne demek?'],
    noun: 'song',
  },
  {
    id: 'a1m-rock-eagles',
    type: 'song',
    title: 'Eagles — Take It Easy',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['rock'],
    why: 'Rock seçtin. Sözler günlük kelimelerden kurulu ve emir kipi çok geçiyor.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'easy', meaning: 'kolay, rahat' },
      { word: 'road', meaning: 'yol' },
      { word: 'to take', meaning: 'almak' },
      { word: 'to stand', meaning: 'durmak' },
    ],
    watchFor: ['Kaç emir cümlesi duydun?', 'Yol ile ilgili hangi kelimeler geçiyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-rock-dylan',
    type: 'song',
    title: 'Bob Dylan — Blowin in the Wind',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['rock'],
    why: 'Rock seçtin. Baştan sona soru cümlesi; "how many" kalıbını şarkıyla öğrenmek hızlı oturuyor.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'wind', meaning: 'rüzgâr' },
      { word: 'road', meaning: 'yol' },
      { word: 'sea', meaning: 'deniz' },
      { word: 'how many', meaning: 'kaç tane' },
    ],
    watchFor: ['Kaç soru cümlesi var?', '"how many" kaç kez geçiyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-pop-perry',
    type: 'song',
    title: 'Katy Perry — Firework',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['pop'],
    why: 'Pop seçtin. Nakarat kısa ve tekrarlı, telaffuz net; sıfatları duyarak öğrenmek için elverişli.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'to show', meaning: 'göstermek' },
      { word: 'sky', meaning: 'gökyüzü' },
      { word: 'bright', meaning: 'parlak' },
      { word: 'to shine', meaning: 'parlamak' },
    ],
    watchFor: ['Nakaratta hangi sıfatlar var?', '"you" kaç kez geçiyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-pop-carpenters',
    type: 'song',
    title: 'The Carpenters — Top of the World',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['pop'],
    why: 'Pop seçtin. Telaffuzu ders kaydı kadar net; kelime ayırt etmek için en kolay parçalardan.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'top', meaning: 'tepe, üst' },
      { word: 'world', meaning: 'dünya' },
      { word: 'to look', meaning: 'bakmak' },
      { word: 'cloud', meaning: 'bulut' },
    ],
    watchFor: ['Kaç kelimeyi ilk dinleyişte yakaladın?', 'Nakarat nerede başlıyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-rap-macklemore',
    type: 'song',
    title: "Macklemore — Can't Hold Us (yalnız nakarat)",
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['rap'],
    why: "Rap seçtin. Kıtalar hızlı ama nakarat yavaş ve tekrarlı; A1'de yalnızca nakarata odaklan.",
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'to hold', meaning: 'tutmak' },
      { word: 'to go', meaning: 'gitmek' },
      { word: 'again', meaning: 'yine, tekrar' },
      { word: 'now', meaning: 'şimdi' },
    ],
    watchFor: ['Nakaratta kaç kelime var?', 'Hangi kelime en çok tekrar ediyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-akustik-jack',
    type: 'song',
    title: 'Jack Johnson — Better Together',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['akustik'],
    why: 'Akustik seçtin. Sakin, sözler kısa cümlelerden kurulu ve konusu somut.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'together', meaning: 'birlikte' },
      { word: 'better', meaning: 'daha iyi' },
      { word: 'thing', meaning: 'şey' },
      { word: 'to love', meaning: 'sevmek' },
    ],
    watchFor: ['"together" kaç kez geçiyor?', 'Hangi kelimeler tekrar ediyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-klasik-bocelli',
    type: 'song',
    title: 'Andrea Bocelli — Time to Say Goodbye',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['klasik'],
    why: 'Klasik seçtin. Sözlerin bir kısmı İtalyanca; İngilizce bölümü çok yavaş ve tek kalıbı tekrarlıyor.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'time', meaning: 'zaman' },
      { word: 'to say', meaning: 'söylemek' },
      { word: 'goodbye', meaning: 'hoşça kal' },
      { word: 'to see', meaning: 'görmek' },
    ],
    watchFor: ['İngilizce bölüm nerede başlıyor?', 'Hangi kalıp tekrar ediyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-metal-nothing',
    type: 'song',
    title: 'Metallica — Nothing Else Matters',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['metal'],
    why: 'Metal seçtin. Metalin en sakin parçası: yavaş başlıyor, telaffuz net ve sözler kısa cümleler.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'to matter', meaning: 'önemli olmak' },
      { word: 'close', meaning: 'yakın' },
      { word: 'to trust', meaning: 'güvenmek' },
      { word: 'never', meaning: 'asla' },
    ],
    watchFor: ['Hangi kelime başlıkta geçiyor?', 'Kaç kısa cümle duydun?'],
    noun: 'song',
  },
  {
    id: 'a1m-blues-etta',
    type: 'song',
    title: 'Etta James — At Last',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['blues'],
    why: 'Blues seçtin. Çok yavaş ve sözler az; her kelimeyi ayrı ayrı duyabiliyorsun.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'at last', meaning: 'sonunda' },
      { word: 'to find', meaning: 'bulmak' },
      { word: 'night', meaning: 'gece' },
      { word: 'sky', meaning: 'gökyüzü' },
    ],
    watchFor: ['Kaç kelime duydun?', 'Nakarat hangi kelimeyle başlıyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-blues-otis',
    type: 'song',
    title: 'Otis Redding — Sittin On The Dock Of The Bay',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['blues'],
    why: 'Blues seçtin. Sakin tempo, günlük kelimeler ve tekrar eden basit bir hikâye.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'to sit', meaning: 'oturmak' },
      { word: 'morning', meaning: 'sabah' },
      { word: 'sun', meaning: 'güneş' },
      { word: 'to watch', meaning: 'izlemek' },
    ],
    watchFor: ['Şarkıcı nerede oturuyor?', 'Hangi fiil tekrar ediyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-caz-sinatra',
    type: 'song',
    title: 'Frank Sinatra — Fly Me to the Moon',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['caz'],
    why: 'Caz seçtin. Kısa cümleler, net telaffuz ve bol bol emir kipi.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'to fly', meaning: 'uçmak' },
      { word: 'moon', meaning: 'ay' },
      { word: 'star', meaning: 'yıldız' },
      { word: 'to play', meaning: 'oynamak' },
    ],
    watchFor: ['Kaç emir cümlesi var?', 'Gökyüzü ile ilgili kaç kelime geçti?'],
    noun: 'song',
  },
  {
    id: 'a1m-country-rogers',
    type: 'song',
    title: 'Kenny Rogers — The Gambler',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['country'],
    why: 'Country seçtin. Baştan sona bir hikâye anlatıyor; tempo yavaş ve cümleler kısa.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'to know', meaning: 'bilmek' },
      { word: 'to hold', meaning: 'tutmak' },
      { word: 'night', meaning: 'gece' },
      { word: 'train', meaning: 'tren' },
    ],
    watchFor: ['Hikâyede kaç kişi var?', 'Hangi fiil en çok tekrar ediyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-metal-evanescence',
    type: 'song',
    title: 'Evanescence — My Immortal',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['metal'],
    why: "Metal seçtin. Piyanoyla söylenen sakin bir parça; metal sevenler için A1'de en kolay giriş.",
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'to hold', meaning: 'tutmak' },
      { word: 'time', meaning: 'zaman' },
      { word: 'face', meaning: 'yüz' },
      { word: 'alone', meaning: 'yalnız' },
    ],
    watchFor: ['Kaç kısa cümle duydun?', 'Hangi kelime tekrar ediyor?'],
    noun: 'song',
  },
  {
    id: 'a1m-metal-nightwish',
    type: 'song',
    title: 'Nightwish — Sleeping Sun',
    where: 'Spotify / YouTube',
    levels: [...A1],
    tastes: ['metal'],
    why: 'Metal seçtin. Yavaş ve temiz bir vokal; sözler doğa kelimelerinden kurulu.',
    instruction: 'Önce sözsüz dinle, nakaratı yakala. Sonra sözleriyle bir daha dinle.',
    words: [
      { word: 'sun', meaning: 'güneş' },
      { word: 'to sleep', meaning: 'uyumak' },
      { word: 'sea', meaning: 'deniz' },
      { word: 'night', meaning: 'gece' },
    ],
    watchFor: ['Doğa ile ilgili kaç kelime geçti?', 'Nakarat nerede başlıyor?'],
    noun: 'song',
  },
];
