/**
 * Düzensiz fiillerin çekimli hâlleri → sözlük hâli.
 *
 * **Neden gerekli:** Google'a tek başına "saw" diye sorunca "testere",
 * "felt" diye sorunca "keçe", "tried" diye sorunca "sınanmış" dönüyor —
 * yazılışı aynı olan başka kelimeyi veriyor. Sözlük hâlini ("see", "feel",
 * "try") ayrıca sorabilmek için bu tabloya ihtiyaç var.
 *
 * Ek kuralla (-ed, -ing, -s) çözülemeyen tek grup düzensiz fiiller olduğu için
 * tablo sadece onları içeriyor. Saf veri, ağ yok, çevrimdışı çalışır.
 *
 * Not: "left", "saw", "felt", "rose" gibi bazıları başlı başına doğru
 * kelimelerdir. O yüzden uygulama **ikisini birden** sorar ve hangisinin
 * doğru olduğuna cümlenin çevirisine bakarak karar verir.
 */
export const IRREGULAR_FORMS: Record<string, string> = {
  was: 'be',
  were: 'be',
  been: 'be',
  became: 'become',
  begun: 'begin',
  began: 'begin',
  bent: 'bend',
  bit: 'bite',
  bitten: 'bite',
  blew: 'blow',
  blown: 'blow',
  broke: 'break',
  broken: 'break',
  brought: 'bring',
  built: 'build',
  bought: 'buy',
  caught: 'catch',
  chose: 'choose',
  chosen: 'choose',
  came: 'come',
  crept: 'creep',
  dealt: 'deal',
  did: 'do',
  done: 'do',
  drew: 'draw',
  drawn: 'draw',
  drank: 'drink',
  drunk: 'drink',
  drove: 'drive',
  driven: 'drive',
  ate: 'eat',
  eaten: 'eat',
  fell: 'fall',
  fallen: 'fall',
  fed: 'feed',
  felt: 'feel',
  fought: 'fight',
  found: 'find',
  flew: 'fly',
  flown: 'fly',
  forgot: 'forget',
  forgotten: 'forget',
  froze: 'freeze',
  frozen: 'freeze',
  got: 'get',
  gotten: 'get',
  gave: 'give',
  given: 'give',
  went: 'go',
  gone: 'go',
  grew: 'grow',
  grown: 'grow',
  hung: 'hang',
  had: 'have',
  heard: 'hear',
  hid: 'hide',
  hidden: 'hide',
  held: 'hold',
  kept: 'keep',
  knew: 'know',
  known: 'know',
  laid: 'lay',
  led: 'lead',
  learnt: 'learn',
  left: 'leave',
  lent: 'lend',
  lain: 'lie',
  lit: 'light',
  lost: 'lose',
  made: 'make',
  meant: 'mean',
  met: 'meet',
  paid: 'pay',
  rode: 'ride',
  ridden: 'ride',
  rang: 'ring',
  rung: 'ring',
  rose: 'rise',
  risen: 'rise',
  ran: 'run',
  said: 'say',
  saw: 'see',
  seen: 'see',
  sought: 'seek',
  sold: 'sell',
  sent: 'send',
  shook: 'shake',
  shaken: 'shake',
  shone: 'shine',
  shot: 'shoot',
  shown: 'show',
  sang: 'sing',
  sung: 'sing',
  sank: 'sink',
  sat: 'sit',
  slept: 'sleep',
  slid: 'slide',
  spoke: 'speak',
  spoken: 'speak',
  spent: 'spend',
  stood: 'stand',
  stole: 'steal',
  stolen: 'steal',
  stuck: 'stick',
  struck: 'strike',
  swept: 'sweep',
  swam: 'swim',
  swum: 'swim',
  took: 'take',
  taken: 'take',
  taught: 'teach',
  tore: 'tear',
  torn: 'tear',
  told: 'tell',
  thought: 'think',
  threw: 'throw',
  thrown: 'throw',
  understood: 'understand',
  woke: 'wake',
  woken: 'wake',
  wept: 'weep',
  wore: 'wear',
  worn: 'wear',
  won: 'win',
  wrote: 'write',
  written: 'write',
};
